In [1]:
import numpy as np
import pandas as pd
from IPython.display import display

In [2]:
df = pd.read_csv('Churn_Modelling.csv')
display(df)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
# Task 4
# Counts: Use value_counts() to count customers by Geography.
# Then count each Geography + Gender combination
# Geography
# Geography + Gender
display(df['Geography'].value_counts())
display('---'*9)
display(df[['Geography','Gender']].value_counts())

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

'---------------------------'

Geography  Gender
France     Male      2753
           Female    2261
Spain      Male      1388
Germany    Male      1316
           Female    1193
Spain      Female    1089
Name: count, dtype: int64

In [4]:
# Task 6
# Replace & map: Create a copy of the DataFrame.
# In the copy, replace Female with F and Male with M using .replace().
# df_copy = df.replace(to_replace=['Male','Female'], value=['M','F']).
# df_copy

# Then solve the same change with .map()
replace_dict = {'Male':'M','Female':'F'}
df_copy_2 = df
df_copy_2['Gender'] = df_copy_2['Gender'].map(replace_dict)
df_copy_2

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,F,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,F,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,F,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,F,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,F,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,M,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,M,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,F,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,M,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,F,28,4,130142.79,1,1,0,38190.78,0

In [5]:
# Task 10
# Largest values plus unique values: Find the 12 customers with the highest EstimatedSalary.
df_copy2 = df.set_index('EstimatedSalary').sort_index(axis = 0, ascending=False).head(12)
# From those rows, print the unique Geography values
display(df_copy2['Geography'].unique())

<StringArray>
['Spain', 'Germany', 'France']
Length: 3, dtype: str

In [15]:
# Task 11
# Missing data: Use the DataFrame below and implement the requested cleaning operations
df_missing = pd.DataFrame({
    'A': [None, 2, 3, None, 5, None],
    'B': [10, None, None, 40, 50, None],
    'C': [100, None, 300, 400, None, None]
})
# 1. Eliminate any row in the DataFrame that contains at least one NaN value
display('1',df_missing.dropna())
# 2.Modify the previous task and eliminate only rows that have NaN values across all columns
display('2',df_missing.dropna(thresh=1))
# 3. Eliminate rows that have at least one NaN in columns A and C only
display('3',df_missing.dropna(subset=['A','C']))
# 4. Replace all NaN values with a specified value of your choice
display('4',df_missing.fillna(0))
# 5. Replace all NaN values in column B with the mean of the non-NaN values in that column
    # two optionsI
        # op numb 1:
# display('5',df_missing.fillna({'B': round(df_missing['B'].mean(),1)}))
        # or op numb 2:
df_missing['B'] = df_missing['B'].fillna(round(df_missing['B'].mean(),1))
display('op2 Q5',df_missing)

'1'

Empty DataFrame
Columns: [A, B, C]
Index: []

'2'

     A     B      C
0  NaN  10.0  100.0
1  2.0   NaN    NaN
2  3.0   NaN  300.0
3  NaN  40.0  400.0
4  5.0  50.0    NaN

'3'

     A   B      C
2  3.0 NaN  300.0

'4'

     A     B      C
0  0.0  10.0  100.0
1  2.0   0.0    0.0
2  3.0   0.0  300.0
3  0.0  40.0  400.0
4  5.0  50.0    0.0
5  0.0   0.0    0.0

'op2 Q5'

     A     B      C
0  NaN  10.0  100.0
1  2.0  33.3    NaN
2  3.0  33.3  300.0
3  NaN  40.0  400.0
4  5.0  50.0    NaN
5  NaN  33.3    NaN